[versions]
# Android
agp = "8.13.1"
androidx-core = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-core-splash-screen = "1.2.0"

# Android Test
junit = "4.13.2"
androidx-junit = "1.3.0"
androidx-espresso-core = "3.7.0"

# Kotlin
kotlin = "2.2.20"
kotlin-coroutines = "1.10.2"
kotlin-serialization-core = "1.9.0"
devtoolsKsp = "2.2.20-2.0.2"

# Android Work
androidx-work = "2.11.0"

# Android Lifecycle
androidx-lifecycle = "2.10.0-alpha06"

# Android Test
androidx-test-runner = "1.7.0"
androidx-test-core = "1.7.0"

# Koin
koin = "4.1.0"
koin-annotations = "2.3.1"

# SquareUp
moshi = "1.15.2"
retrofit = "3.0.0"
okhttp3 = "5.1.0"
okhttp3Logging = "5.1.0"
seismic = "1.0.3"

# Compose
compose-bom = "2025.12.00"
compose-multiplatform = "1.10.0"
compose-hot-reload = "1.1.0-alpha01"
compose-compiler = "2.3.0"
compose-activity = "1.12.2"
accompanistPermission = "0.37.3"

# Material Icons
material-icons = "1.7.3"

# Material 3
material3 = "1.10.0-alpha05"
material3-adaptive = "1.3.0-alpha02"

# Jetbrains Navigation
navigation2 = "2.9.1"

# Jetbrains Navigation 3
navigation3 = "1.0.0-alpha06"

# Jetbrains Saved State
savedstate = "1.4.0"

[libraries]
# Android
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splash-screen" }

# Android Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Kotlin Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }

# Kotlin Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-core" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlin-serialization-core" }

# Koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-androidx-navigation = { group = "io.insert-koin", name = "koin-androidx-navigation", version.ref = "koin" }

# Koin Annotiations
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-annotations" }

# Android Work
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }

# Android Lifecycle
androidx-lifecycle-common = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }

# Compose Activity
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }

# Compose Resource
jetbrains-compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }

# Compose UI
jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-multiplatform" }

# Compose UI Tooling Preview
jetbrains-compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-multiplatform" }
jetbrains-compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }

# Compose UI Uikit
jetbrains-compose-ui-uikit = { group = "org.jetbrains.compose.ui", name = "ui-uikit", version.ref = "compose-multiplatform" }

# Compose Runtime
jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }

# Compose Foundation
jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }

# Compose Foundation Layout
jetbrains-compose-foundation-layout = { group = "org.jetbrains.compose.foundation", name = "foundation-layout", version.ref = "compose-multiplatform" }

# Compose Material
jetbrains-material = { group = "org.jetbrains.compose.material", name = "material", version.ref = "compose-multiplatform" }

# Compose Material Icons
jetbrains-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "material-icons" }

# Compose Material 3
jetbrains-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }

# Compose Material 3 Window Size Class
jetbrains-material3-window-size = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3" }

# Compose Material 3 Adaptive
jetbrains-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3",  version.ref = "material3-adaptive" }

# Jetbrains Compose Navigation
jetbrains-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation2" }

# Jetbrains Navigation Runtime
jetbrains-navigation-runtime = { group = "org.jetbrains.androidx.navigation", name = "navigation-runtime", version.ref = "navigation2" }

# Jetbrains Navigation 3
jetbrains-navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }

# Jetbrains Saved State
jetbrains-androidx-savedstate = { group = "org.jetbrains.androidx.savedstate", name = "savedstate", version.ref = "savedstate" }

# Jetbrains Compose Saved State
jetbrains-androidx-savedstate-compose = { group = "org.jetbrains.androidx.savedstate", name = "savedstate-compose", version.ref = "savedstate" }

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Kotlin
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }
